# Generated by Django 3.2.8 on 2023-02-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoDocumento',
            new_name='Tdocumento',
        ),
    ]
